# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: haydenbanz/metrics@hades
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: haydenbanz
          template: classic
          
          config_timezone: Asia/Kolkata
          plugin_anilist: yes
          plugin_anilist_limit: 6
          plugin_anilist_limit_characters: 19
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites
          plugin_anilist_shuffle: yes
          plugin_anilist_user: hayzu
          plugin_music: yes
          plugin_music_limit: 40
          plugin_music_mode: playlist
          plugin_music_playlist: https://open.spotify.com/embed/playlist/3ydgiFwK8q40zPm93V0kRX?utm_source=generator
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_rss: yes
          plugin_rss_limit: 6
          plugin_rss_source: https://raw.githubusercontent.com/haydenbanz/haydenbanz.github.io/refs/heads/main/rss.xml
          plugin_tweets: yes
          plugin_tweets_limit: 2
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_user: sudo_entityz
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_url: https://wakatime.com/@haydenbanz
          plugin_wakatime_user: current
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: haydenbanz


