# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: haydenbanz/metrics@hades
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: hades
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_anilist: yes
          plugin_anilist_limit: 6
          plugin_anilist_limit_characters: 19
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites
          plugin_anilist_shuffle: yes
          plugin_music: yes
          plugin_music_limit: 40
          plugin_music_mode: playlist
          plugin_music_playlist: https://open.spotify.com/playlist/3ydgiFwK8q40zPm93V0kRX?si=62805fb670684324
          plugin_music_provider: spotify
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: 31xpiaan6exwxfrbwwjraj4e4uxy
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_rss: yes
          plugin_rss_limit: 6
          plugin_rss_source: https://medium.com/feed/@hades
          plugin_tweets: yes
          plugin_tweets_limit: 2
          plugin_tweets_user: sudo_entity
